services:
  api:
    image: lwjerri/telegram-bot-api-s3:latest
    restart: unless-stopped
    environment:
      TELEGRAM_API_ID: "XXX"
      TELEGRAM_API_HASH: "YYY"
      #TELEGRAM_LOCAL: 1  # allow files >20mb
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api

  nginx:
    image: nginx:1.27.3-alpine
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"

volumes:
  telegram-bot-api-data:
