services:
  api:
    image: aiogram/telegram-bot-api:latest
    restart: unless-stopped
    environment:
      TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
      TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
      #TELEGRAM_LOCAL: 1  # allow files >20mb

      S3_BUCKET: "${S3_BUCKET}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
    tmpfs:
      - /var/lib/telegram-bot-api:size=2G
      - /tmp/telegram-bot-api:size=2G
    ports:
      - "8081:8081"

  nginx:
    image: nginx:1.27.3-alpine
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
